export declare const active: string;
export declare const card: string;
export declare const cardContainer: string;
export declare const cardImage: string;
export declare const cardImageContainer: string;
export declare const cardWrapper: string;
export declare const focused: string;
export declare const link: string;
export declare const popupOverlay: string;
