export declare const dropDown: string;
export declare const image: string;
export declare const linkedImage: string;
export declare const mainContainer: string;
export declare const pageIntro: string;
export declare const pageTitle: string;
export declare const pageTitleWrapper: string;
export declare const popUp: string;
export declare const text: string;
