export declare const container: string;
export declare const content: string;
export declare const header: string;
export declare const icon: string;
export declare const image: string;
export declare const inputBox: string;
export declare const messageBox: string;
export declare const text: string;
export declare const user: string;
